# Site settings
title: Techquila
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An occassionally updated blog about XML, Semantic Web standards, and photography.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://techquila.com" # the base hostname & protocol for your site
twitter_username: kal_ahmed
github_username:  kal

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"